version: "3"


services:
  backend:
    build:
      context: services/backend
    image: backend:todo
    restart: always
    ports:
      - 8001:8000
    env_file:
      - services/backend/.env
    volumes:
      - ./services/backend/service:/app

  frontend:
    build:
      context: services/frontend
    image: frontend:todo
    restart: always
    ports:
      - 8000:8080
    env_file:
      - services/backend/.env
    volumes:
      - ./services/frontend/service:/app
    depends_on:
      - backend
